### ISSUE TITLE
Won't run with OpenJDK 11.0.8

### ISSUE THREAD

**Issue by jdjohnston** [akka/akka-quickstart-scala.g8#54]
Per build.sbt:
scalaVersion := "2.13.1"
akkaVersion = "2.6.10"

This was run on Xubuntu 18.04 with OpenJDK 11.0.8.

To get a quickstart zip, I followed the directions at the [Lightbend Tech Hub](https://developer.lightbend.com/start/?group=akka&project=akka-quickstart-scala)

When I tried to run sbt, there was an error message that at least Java 1.6+ was required. Somehow 11.0.8 was seen as less than 1.6 . I commented out the version check and everything ran fine.

Perhaps this is actually an issue with sbt, but the end result is that without poking around in `sbt-dist/bin/sbt-launch-lib.bash`, I wouldn't have been able to run the quickstart example.

**Comment by raboof** [comment]
That sounds weird. What version of the `sbt` script are you running? (`sbt --version`)?

**Comment by jdjohnston** [comment]
I'm away from my computer at the moment, but it was the sbt bundled with the quickstart code. 

I'll check it & report back, but it will be a couple of days.

**Comment by jdjohnston** [comment]
The sbt (version 1.4.1) I have on $PATH works fine with the quickstart code, but the instructions I was following said to use the sbt in the zipfile.

./sbt --version just generates an error.

 in the zipfile has 1 line:
sbt.version

**Comment by raboof** [comment]
Thanks for clarifying, I can indeed reproduce the problem with the sbt shipped in the .zip. I suspect we need to upgrade the sbt launcher we put in the zip.

Until that time, as a short-term solution, you can install a newer version of sbt yourself from https://www.scala-sbt.org/download.html and use that.

**Comment by ignasi35** [comment]
> Thanks for clarifying, I can indeed reproduce the problem with the sbt shipped in the .zip. I suspect we need to upgrade the sbt launcher we put in the zip.

Maybe even improve the CI build to use that script instead of the `sbt` command provided by the VM.

**Comment by raboof** [comment]
> Maybe even improve the CI build to use that script instead of the `sbt` command provided by the VM.

This `sbt` command is added when the zip is created, so it's not yet available in the CI for this repo.

**Comment by raboof** [comment]
@jdjohnston this should now be fixed, thanks so much for the heads-up! feel free to ping if you see any further problems.

**Comment by jdjohnston** [comment]
@raboof , just confirming that it works on my computer as well

**Comment by raboof** [comment]
Great, thanks!
